install:
	poetry install
brain-games:
	poetry run brain-games
brain-even:
	poetry run brain-even
package-install:
	python3 -m pip install --user dist/*.whl
lint:
	poetry run flake8 /home/hexlet-git/python-project-49/brain_games
